### ISSUE TITLE
Error appeared using the latest commit

### ISSUE THREAD

**Issue by hexh250786313** [rockyzhang24/arctic.nvim#10]
neovim version: 0.9.5
os: Manjaro Linux x86_64 6.1.71-1-MANJARO

The plugin worked well in the past, but something went wrong with the latest commit https://github.com/rockyzhang24/arctic.nvim/commit/7297a66075f9b27ba73d5ee4ba8a831cf5de34d8 on both the main and v2 branches.

```vimscript
" mini.vim
set runtimepath^=/home/hexh/Desktop/arctic.nvim/arctic.nvim
set runtimepath^=/home/hexh/Desktop/arctic.nvim/lush.nvim

colorscheme arctic
```

```sh
nvim --clean -u ./mini.vim ./mini.vim
```

![image](https://github.com/rockyzhang24/arctic.nvim/assets/26080416/f71cd166-192f-4790-a21f-4cf1d5a79491)

**Comment by hexh250786313** [comment]
IDK is it related to treesitter. I don't use treesitter.

**Comment by rockyzhang24** [comment]
Should fixed. Sorry for my carelessness.

**Comment by hexh250786313** [comment]
@rockyzhang24 Ty for fixing. It helps for me and issue closed.
