### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by pbower** [rockyzhang24/arctic.nvim#11]
Hi there,

When activating the colourscheme, with the required dependencies installed, I get "E5113: Error while calling lua chunk: [NULL]."

I'm using Vimplug.

Have you encountered this type of thing before?

I'm on Neovim v0.9.5

Thanks

**Comment by rockyzhang24** [comment]
Sorry it's my bad. Fixed it already 1ed00a7a78c3dfdd39b2d5b223822a160bb4b843.

**Comment by pbower** [comment]
Brilliant, thanks for that! Something else I noticed is the 'def' in 'def my_func()' in python is purple rather than medium blue. Additionally, the Function arguments are white rather than light blue as they are in VS Code.

Is this the expected behaviour ?

Thanks,
Pete

**Comment by rockyzhang24** [comment]
The basic syntax highlight engines are different, VS Code uses textmate grammars for syntax highlight, whereas Neovim uses treesitter. So some minor differences are expected. If you want it to be as much identical as VS Code, you could fork this repo and modify the colors for specific language. For example, `@keyword.python` will define the highlight color for the keywords only for python. Hope it's helpful 👊
