### ISSUE TITLE
error occurred when installing

### ISSUE THREAD

**Issue by jinzhongjia** [rockyzhang24/arctic.nvim#6]
- neovim version: `nightly`
- package manager: `lazy.nvim`
- branch: `v2`

Like this:
![image](https://github.com/rockyzhang24/arctic.nvim/assets/41784264/8a46c4ba-1a92-471c-8bfb-46b878bafbb0)

I don’t know why lazy redraw is triggered. And the problem cannot be reproduced stably

**Comment by jinzhongjia** [comment]
Either this error is reported or neovim crashes.

**Comment by jinzhongjia** [comment]
After the installation is complete, there is no error when re-entering. It only occurs during the initial installation.

**Comment by jinzhongjia** [comment]
I retested the installation under the stable version and everything worked fine, it looks like the recent neovim changed something

**Comment by rockyzhang24** [comment]
I am not using lazy.nvim to manage my plugins, so I have no ideas regarding the errors. Sorry about that. This plugin is built on and fully backed by [lush.nvim](https://github.com/rktjmp/lush.nvim). I just defined colors and groups. All the functions and mechanisms are from lush.nvim. Probably some changes in the neovim core disrupted lush.nvim.

Actually I have extracted this theme to a separate file in my own nvim configs and make it independent of lush.nvim. I will link it here for you later.

Thank you.

**Comment by rockyzhang24** [comment]
I decoupled arctic and lush. Here you go https://github.com/rockyzhang24/dotfiles/blob/master/.config/nvim/colors/arctic.lua

**Comment by jinzhongjia** [comment]
thx, I'll try it now

**Comment by jinzhongjia** [comment]
Everything looks fine now
