### ISSUE TITLE
Theme misses colors

### ISSUE THREAD

**Issue by Lauel09** [rockyzhang24/arctic.nvim#9]
Hello!
Thank you making such a theme for neovim (I love dark vscode themes too).
I installed the theme on the unstable nvim with this version:
```bash
➜ nvim --version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
I am using `Lazy.nvim` plugin manager.
This is my config:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
local plugins = {
    {"blazkowolf/gruber-darker.nvim", event = "VimEnter"},
    { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
    {
        "rockyzhang24/arctic.nvim",
        branch = "v2",
        dependencies = { "rktjmp/lush.nvim" }
    }
}
vim.opt.rtp:prepend(lazypath)
require("lazy").setup(plugins, opts)
vim.cmd("colorscheme arctic") 
vim.g.mapleader = " "
```
This is the screenshot:-
![image](https://github.com/rockyzhang24/arctic.nvim/assets/19989996/82404966-0f2e-4be5-8011-9a1bdf0cee87)
This is missing shades of Green, and comments color.
I have tried changing the terminal to gnome-terminal, still no avail. Currently I am using alacritty.
Thank you!

**Comment by rockyzhang24** [comment]
Seems the 24-bits colors is not enabled in your tmux config. Try it outside the tmux first please.

**Comment by rockyzhang24** [comment]
If it works well outside tmux, put the code below into your tmux config and then try it again inside tmux.

```
set -g default-terminal "tmux-256color"
set -sa terminal-features ",xterm-256color:RGB"
set -ga terminal-overrides ",alacritty:RGB"
```

**Comment by Lauel09** [comment]
Thank you for the reply!

> Seems the 24-bits colors is not enabled in your tmux config. Try it outside the tmux first please.

Running outside tmux:
![image](https://github.com/rockyzhang24/arctic.nvim/assets/19989996/14464226-4d93-43d3-8640-0f2dd69664d4)

Running inside tmux, after making the changes you recommended but unfortunately the result is the same:
![image](https://github.com/rockyzhang24/arctic.nvim/assets/19989996/c097f07b-0dd5-42cb-825b-1bf4f5b6aedf)

**Comment by rockyzhang24** [comment]
Do you have nvim-treesitter and LSP servers installed? To get rich colors, these two are required.

**Comment by Lauel09** [comment]
> Do you have nvim-treesitter and LSP servers installed? To get rich colors, these two are required.

Thank you, that fixed it. Had to install both plugins for theme to work properly.
Looks lovely now:
![image](https://github.com/rockyzhang24/arctic.nvim/assets/19989996/4e8f470b-cc2e-4bb3-b987-573fb2dabca4)


Also if you don't mind me asking, what plugins is the screenshot using?

**Comment by rockyzhang24** [comment]
> what plugins is the screenshot using?

Do you mean the screenshot in README? You can find all the plugins I'm using in [my nvim config repo](https://github.com/rockyzhang24/dotfiles/tree/master/.config/nvim).
